### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by edravis** [yeoman/generator-node#103]
I've just installed and it has failed with `yo node` then I've search some information and I've found the #53 so I've installed the generator by using `npm i generator-node@0.4.2 -g` and it works.

I'm suggesting to add this information in the README.md or change the stable version to 0.4.2

**Comment by kevva** [comment]
The current version should work just fine. Current version is 0.7.0.

**Comment by edravis** [comment]
Should but don't. I've already checked in another computer.

First test: Mac OSX Yosemite 10.10
Second test: Xubuntu 14.04

Both cases: npm 2.6.0

**Comment by kevva** [comment]
What errors are you receiving? I just ran it on Ubuntu without any problems.

**Comment by edravis** [comment]
```
~ yo node

/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:445:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:319:20)
    at /usr/local/lib/node_modules/yo/cli.js:110:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:49:32)
    at init (/usr/local/lib/node_modules/yo/cli.js:86:7)
    at pre (/usr/local/lib/node_modules/yo/cli.js:64:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/cli.js:161:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by kevva** [comment]
Yes, might be. @SBoudrias?

**Comment by SBoudrias** [comment]
Update `yo`
