### ISSUE TITLE
Clean `yo node` fails

### ISSUE THREAD

**Issue by voltrevo** [yeoman/generator-node#180]
```
Andrews-MacBook-Pro:eslint-plugin-filesize andrew$ yo node
? Module Name: eslint-plugin-filesize
? Description: An eslint plugin that limits the minified + gzipped size of a file.
? Project homepage url: 
? Author's Name: Andrew Morris
? Author's Email: voltrevo@gmail.com
? Author's Homepage: https://andrewmorris.io/
? Package keywords (comma to split) eslint,plugin,filesize,minify,gzip,code,quality,metric
? Use es2015 (precompiled with Babel) No
? Send coverage reports to coveralls: Yes
? GitHub username or organization: voltrevo
? Which license do you want to use? MIT
   create package.json
   create README.md
   create .travis.yml
   create .editorconfig
   create .gitattributes
   create .gitignore
   create .eslintrc
   create gulpfile.js
   create lib/index.js
   create test/index.js
   create LICENSE
npm WARN deprecated gulp-nsp@0.4.5: new api version released, version 2.0.0 or greater required

> eslint-plugin-filesize@0.0.0 prepublish /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize
> gulp prepublish

[10:13:43] Using gulpfile ~/workspaces/hackday-2015-11-02/eslint-plugin-filesize/gulpfile.js
[10:13:43] Starting 'nsp'...
/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:59
    return m ? m.index + 1 : c.length;
                              ^
TypeError: Cannot read property 'length' of undefined
    at dotindex (/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:59:31)
    at /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:11:21
    at Array.forEach (native)
    at forEach (/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:73:31)
    at /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:10:9
    at Array.reduce (native)
    at reduce (/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:63:30)
    at module.exports (/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/text-table/index.js:9:20)
    at prettyOutput (/Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/gulp-nsp/lib/prettyOutput.js:30:11)
    at /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/node_modules/gulp-nsp/index.js:34:36

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/andrew/npm/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE
npm ERR! eslint-plugin-filesize@0.0.0 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eslint-plugin-filesize@0.0.0 prepublish script 'gulp prepublish'.
npm ERR! This is most likely a problem with the eslint-plugin-filesize package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get their info via:
npm ERR!     npm owner ls eslint-plugin-filesize
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/npm-debug.log
Initialized empty Git repository in /Users/andrew/workspaces/hackday-2015-11-02/eslint-plugin-filesize/.git/
```

It looks like `gulp-nsp` is passing `undefined`s to `text-table`, which it gets from `module.advisory.patched_versions` and `module.advisory.url`. `gulp-nsp` has updated to 2.0.0 now and the fix may be to update the dependency, although I got a different problem (lost the output sorry, can probably reproduce if you need it) when I tried that so a bit of extra legwork may be involved.

PS: npm version 3.3.3, node version v0.12.2.

**Comment by hemanth** [comment]
Thanks for the report.

After updating `gulp-nsp` are you noticing the same?

P.S: I am yet to reproduce your issue.

**Comment by voltrevo** [comment]
I get this when updating to 2.0.0:

```
Andrews-MacBook-Pro:foo-project andrew$ gulp nsp
[17:12:13] Using gulpfile ~/workspaces/generator-node-issue-180/foo-project/gulpfile.js
[17:12:13] Starting 'nsp'...
[17:12:14] 'nsp' errored after 4.28 ms
[17:12:14] Error: (+) ValidationError: "value" must contain at least one of [package, shrinkwrap]
    at formatError (/Users/andrew/npm/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/andrew/npm/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/orchestrator/index.js:264:8)
    at /Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/orchestrator/index.js:275:23
    at finish (/Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/orchestrator/lib/runTask.js:29:3)
    at /Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/gulp-nsp/index.js:23:14
    at Object.module.exports [as check] (/Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/gulp-nsp/node_modules/nsp/lib/check.js:83:12)
    at rsGulp (/Users/andrew/workspaces/generator-node-issue-180/foo-project/node_modules/gulp-nsp/index.js:20:7)
```

**Comment by SBoudrias** [comment]
Can you test the latest version? (0.6.1)

**Comment by voltrevo** [comment]
@SBoudrias Yep works for me now :+1:.

**Comment by amatosc** [comment]
I had the same error, I to upgrade it to v2.1.0 (because the v0.6.1, but it not available now). I got this error:
`[11:46:28] Starting 'nsp'...
[11:46:28] 'nsp' errored after 4.77 ms
[11:46:28] Error in plugin 'gulp-nsp'
Message:
    (+) ValidationError: "value" must contain at least one of [package, shrinkwrap]` 
node: v0.12.7
npm: 3.5.4

`npm-debug.log (a bit)`
`76 verbose stack Error: data-science@0.0.1 prepublish: `gulp prepublish`
76 verbose stack Exit status 1
76 verbose stack     at EventEmitter.<anonymous> (/home/alex/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
76 verbose stack     at EventEmitter.emit (events.js:110:17)
76 verbose stack     at ChildProcess.<anonymous> (/home/alex/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
76 verbose stack     at ChildProcess.emit (events.js:110:17)
76 verbose stack     at maybeClose (child_process.js:1015:16)
76 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
77 verbose pkgid data-science@0.0.1
78 verbose cwd /home/alex/development/amatosc/data-science
79 error Linux 3.16.0-57-generic
80 error argv "node" "/home/alex/.nvm/versions/node/v0.12.7/bin/npm" "install"
81 error node v0.12.7
82 error npm  v3.5.4
83 error code ELIFECYCLE
84 error data-science@0.0.1 prepublish: `gulp prepublish`
84 error Exit status 1
85 error Failed at the data-science@0.0.1 prepublish script 'gulp prepublish'.
85 error Make sure you have the latest version of node.js and npm installed.
85 error If you do, this is most likely a problem with the data-science package,
85 error not with npm itself.
85 error Tell the author that this fails on your system:
85 error     gulp prepublish
85 error You can get information on how to open an issue for this project with:
85 error     npm bugs data-science
85 error Or if that isn't available, you can get their info via:
85 error     npm owner ls data-science
85 error There is likely additional logging output above.
86 verbose exit [ 1, true ]`

**Comment by SBoudrias** [comment]
Will investigate... maybe nsp pushed a breaking change?

**Comment by amatosc** [comment]
Mmm.. I don't know, I tried with some differents versions and I got the same error in all my tests

**Comment by SBoudrias** [comment]
@amatosc just tried on the latest version and couldn't reproduce. Are you sure you didn't modify nsp in any ways? Can you copy paste your gulpfile.js here?

**Comment by amatosc** [comment]
@SBoudrias It worked but I just updated and it stopped working. Of course! but I checked my git log for to be sure that I have not touched and I didn't. Thanks a lot.

```
'use strict';
var gulp = require('gulp');
var eslint = require('gulp-eslint');
var excludeGitignore = require('gulp-exclude-gitignore');
var mocha = require('gulp-mocha');
var istanbul = require('gulp-istanbul');
var nsp = require('gulp-nsp');
var plumber = require('gulp-plumber');

gulp.task('static', function () {
  return gulp.src('**/*.js')
    .pipe(excludeGitignore())
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});

gulp.task('nsp', function (cb) {
  nsp('package.json', cb);
});

gulp.task('pre-test', function () {
  return gulp.src('lib/**/*.js')
    .pipe(istanbul({
      includeUntested: true
    }))
    .pipe(istanbul.hookRequire());
});

gulp.task('test', ['pre-test'], function (cb) {
  var mochaErr;

  gulp.src('test/**/*.js')
    .pipe(plumber())
    .pipe(mocha({reporter: 'spec'}))
    .on('error', function (err) {
      mochaErr = err;
    })
    .pipe(istanbul.writeReports())
    .on('end', function () {
      cb(mochaErr);
    });
});

gulp.task('prepublish', ['nsp']);
gulp.task('default', ['static', 'test']);
```

**Comment by SBoudrias** [comment]
@amatosc I'd open an issue on gulp-nsp. It's really working fine here, so it must be something on your system.

Maybe you have nsp somewhere global and that conflicts? Maybe you deleted your package.json? or maybe a package in your package.json is causing an issue with the nsp parser...

**Comment by amatosc** [comment]
@SBoudrias I've fixed it changing this:
```
gulp.task('nsp', function (cb) {
  nsp('/package.json', cb);
});
```
 to:
```
gulp.task('nsp', function (cb) {
  nsp({package: __dirname + '/package.json'}, cb);
});
```
