### ISSUE TITLE
Error is thrown if we can't get an email

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#185]
Saw this error while trying to run `generator-generator` on top of the `generator-generator` project.

```

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: `email` required
    at module.exports (/Users/sboudrias/github/generator-generator/node_modules/github-username/index.js:6:9)
    at module.exports.generators.Base.extend.prompting.askForGithubAccount (/Users/sboudrias/github/generator-generator/node_modules/generator-node/generators/app/index.js:162:7)
    at /Users/sboudrias/github/generator-generator/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Not sure what's up, but this for sure shouldn't throw.

**Comment by SBoudrias** [comment]
The fix should be easy, we're not asking for the email if the package.json field have an `author`. But we should ask if we haven't been able to find an email (the author field might only contain a name, or might be broken).

**Comment by hemanth** [comment]
Just `email` would be fine? As we could get the `npm-name` from the it.

**Comment by hemanth** [comment]
:+1:

**Comment by montanaflynn** [comment]
I just got thrown an error when I didn't add an email:

```
? Module Name some-thing
? Description
? Project homepage url
? Author's Name
? Author's Email
? Author's Homepage
? Package keywords (comma to split)
? Use es2015 (precompiled with Babel) Yes
? Send coverage reports to coveralls No
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: `email` required
    at module.exports (/usr/local/lib/node_modules/generator-node/node_modules/github-username/index.js:6:9)
    at module.exports.generators.Base.extend.prompting.askForGithubAccount (/usr/local/lib/node_modules/generator-node/generators/app/index.js:175:7)
    at /usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by SBoudrias** [comment]
@montanaflynn are you sure you're on the latest version?

**Comment by montanaflynn** [comment]
No, but I had just installed yeoman and generator-node immediately prior to generating the error.

```
npm install -g yo
npm install -g generator-node
yo node
```

**Comment by SBoudrias** [comment]
Okay, we'll re-investigate.

**Comment by eddiemonge** [comment]
Closing this as a default email is put in now

**Comment by jessefulton** [comment]
Getting errors here too:
```
vagrant@localhost /vagrant/tmp $ yo node
? Module Name tmp
? The name above already exists on npm, choose another? No
? Description 
? Project homepage url 
? Author's Name 
? Author's Email 
? Author's Homepage 
? Package keywords (comma to split) 
? Use es2015 (precompiled with Babel) Yes
? Send coverage reports to coveralls No
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Email required
    at module.exports.ghGot.then (/usr/lib/node_modules/generator-node/node_modules/github-username/index.js:6:9)
    at module.exports.generators.Base.extend.prompting.askForGithubAccount (/usr/lib/node_modules/generator-node/generators/app/index.js:187:14)
    at Object.<anonymous> (/usr/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/lib/node_modules/generator-node/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/generator-node/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

```
vagrant@localhost /vagrant/tmp $ node -v
v4.7.0
vagrant@localhost /vagrant/tmp $ npm -v
2.15.11
vagrant@localhost /vagrant/tmp $ npm ls -g --depth=0
/usr/lib
├── generator-node@1.12.1
├── npm@2.15.11
└── yo@1.8.5
```

**Comment by eddiemonge** [comment]
I have nearly the same versions and I didn't get that error

**Comment by eddiemonge** [comment]
@jessefulton do you have anything in `git config --global user.name` or `git config --global user.email`?

**Comment by mischah** [comment]
🔔 @jessefulton

**Comment by SBoudrias** [comment]
I think that's fixed now that the API uses promises. And we handle the error case. I'll close unless someone still reports it broken.
