### ISSUE TITLE
yo node:gulp is breaking.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-node#191]
```sh
$ yo node:gulp .
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at module.exports.generators.Base.extend.writing.gulpfile (/Users/Hemanth/.nvm/versions/node/v5.1.0/lib/node_modules/generator-node/generators/gulp/index.js:91:29)
    at /Users/Hemanth/.nvm/versions/node/v5.1.0/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by hemanth** [comment]
It must be `yo node:gulp --projectRoot .` need to update the doc.
