### ISSUE TITLE
error line number in test

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#218]
reported error line 38
```bash
 1) cli config should be able to config host:

      Uncaught AssertionError: true == false
      + expected - actual

      -true
      +false
      
    at Test.<anonymous> (test/cli.js:38:16)
    at Test.assert (node_modules/supertest/lib/test.js:156:6)
    at Server.assert (node_modules/supertest/lib/test.js:127:12)
    at emitCloseNT (net.js:1521:8)
```

actual line number: 45

**Comment by eddiemonge** [comment]
Unable to reproduce this
