### ISSUE TITLE
this.pkg.repository.indexOf is not a function

### ISSUE THREAD

**Issue by jamen** [yeoman/generator-node#224]
I'm getting an error, when trying to use this generator...

```
Reinitialized existing Git repository in ~/projects/jamen/hmu/.git/
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.pkg.repository.indexOf is not a function
    at module.exports.generators.Base.extend.end (~/.npm-global/lib/node_modules/generator-node/generators/git/index.js:73:31)
    at Object.<anonymous> (~/.npm-global/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:436:25)
    at ~/.npm-global/lib/node_modules/generator-node/node_modules/run-async/index.js:24:25
    at ~/.npm-global/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jamen** [comment]
Everything seems to have generated fine though.
