### ISSUE TITLE
Cannot find module 'eslint-config-xo'

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#241]
```
> test@0.0.0 test 
> gulp

[14:02:47] Using gulpfile ~/Sites/t1bao.com/server/vli/gulpfile.js
[14:02:47] Starting 'static'...
[14:02:47] Starting 'pre-test'...
/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: Cannot find module 'eslint-config-xo'
Referenced from: xo-space
Referenced from: package.json
    at Object.ModuleResolver.resolve (/node_modules/gulp-eslint/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:496:24)
    at /node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:530:22)
    at /node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:363:28)
npm ERR! Test failed.  See above for more details.
```

**Comment by calidion** [comment]
after 
```
npm install --save-dev eslint-config-xo
```
executed. got this error.

```
gulp
[14:06:10] Using gulpfile gulpfile.js
[14:06:10] Starting 'static'...
[14:06:10] Starting 'pre-test'...
/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: xo:
	Configuration for rule "valid-typeof" is invalid:
	Value "[object Object]" has more items than allowed.

Referenced from: xo-space
Referenced from: /package.json
    at validateRuleOptions (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:116:15)
    at /node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:163:13
    at Array.forEach (native)
    at Object.validate (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:162:35)
    at load (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:523:19)
    at /node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:530:22)
    at /node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:392:36
```

**Comment by sindresorhus** [comment]
You need to update ESLint. Reinstalling your dependencies should fix it.

**Comment by calidion** [comment]
it is assumed to be working by default.

**Comment by calidion** [comment]
and it is useless to install the lastest version of eslint.

**Comment by SBoudrias** [comment]
@calidion my guess is you didn't update the right eslint version. There's the local one and the global one.

**Comment by calidion** [comment]
how to install the right version?

**Comment by calidion** [comment]
if 
```
npm install
```
will install a false version.
I think it is a problem fo generator-node.
i am not using eslint.
I just need a scaffolding program to accelerate my development.

**Comment by SBoudrias** [comment]
@calidion if you don't want linting, then just remove the eslint task in your gulpfile.

If you want it, update eslint version inside your `package.json`.

**Comment by calidion** [comment]
@SBoudrias 
I have updated to the latest version. but it is still not working..

**Comment by SBoudrias** [comment]
@calidion I don't know what to tell you, I just tried on the latest generator-node release and everything is working fine on my end.

Maybe you're running on an old node version or something and that's breaking something?

**Comment by calidion** [comment]
maybe you should try with npm2

**Comment by calidion** [comment]
node --version
v4.5.0
npm --version
2.15.9

**Comment by calidion** [comment]
it works after executing
```
ncu -u
```
