### ISSUE TITLE
Getting error while running yo node

### ISSUE THREAD

**Issue by dnafication** [yeoman/generator-node#290]
Getting following error while running `yo node`. I am on macOS 11.1, node v12.16 through `nvm`

``` bash
 yo node
? Module Name test
(node:40597) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
HTTPError: Response code 401 (Unauthorized)
    at /Users/dina/.nvm/versions/node/v12.16.3/lib/node_modules/generator-node/node_modules/npm-name/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
HTTPError: Response code 401 (Unauthorized)
    at /Users/dina/.nvm/versions/node/v12.16.3/lib/node_modules/generator-node/node_modules/npm-name/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by JoshuaKGoldberg** [comment]
~4 years since posting and no other responses. Whatever the issue is, it's not something specific to `generator-node`. It's something to do with the options & requests as sent by `yo` / `yeoman-generator`. A few networking/proxy-related issues have previously been noted in `yo`: at least https://github.com/yeoman/yo/issues/612, https://github.com/yeoman/yo/issues/616. I'm going to go ahead and close this one out as external to `generator-node`.

If someone is still seeing this issue, please do file a new issue on https://github.com/yeoman/yo with as much detail as possible, including your system information and a full reproduction (https://antfu.me/posts/why-reproductions-are-required). Cheers! 🎩
