### ISSUE TITLE
`generator.run is not a function` when i use yo@5.0.0

### ISSUE THREAD

**Issue by dribble-njr** [yeoman/generator-node#296]
## Environment

- Node version: v18.17.0 
- npm version: 9.6.7
- Version of yo : 5.0.0

## behavior

Run the following code:

```shell
yo node
```

After I complete the questions, it happens an error:

<img width="233" alt="image" src="https://github.com/yeoman/generator-node/assets/72367140/c3cf8139-bf80-4031-8828-49dda530793f">

Accoring to [issue796](https://github.com/yeoman/yo/issues/796), maybe the `yeoman-generator` version is too old.

**Comment by JoseCarlosGZ** [comment]
I got the same error. I would appreciate some support 😊👌

**Comment by YadOwO** [comment]
I got the same error too

**Comment by YadOwO** [comment]
node 20.17.0
npm 10.8.2
yo 5.1.0

macOS 15.1.1

**Comment by ntt77** [comment]
same issue. and I can't use other way because SharePoint is required to use this

**Comment by JoshuaKGoldberg** [comment]
👋 Hi all! We're resuming maintenance on Yeoman and picking up old issues like this one. See https://github.com/yeoman/yeoman/issues/1779. 

I can reproduce this locally with:

```shell
npm i -g yo generator-node
yo node
```

```plaintext
yo node
(node:76706) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
? Module Name yotest
(node:76706) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
? The name above already exists on npm, choose another? No
? Description 
? Project homepage url 
? Author's Name Josh Goldberg
? Author's Email git@joshuakgoldberg.com
? Author's Homepage 
? Package keywords (comma to split) 
? Send coverage reports to coveralls Yes
? Enter Node versions (comma separated) 
? GitHub username or organization JoshuaKGoldberg
Error node 

generator.run is not a function
```

I think this issue is similar to https://github.com/yeoman/generator-generator/issues/258. Both generators are using old versions of Yeoman dependencies.

I tried updating the `yeoman-generator` dependency to the latest `^7.4.0` but was hit with the always-lovely:

```plaintext
require() of ES Module /Users/josh/repos/generator-node/node_modules/yeoman-generator/dist/index.js from /Users/josh/repos/generator-node/generators/app/index.js not supported.
Instead change the require of /Users/josh/repos/generator-node/node_modules/yeoman-generator/dist/index.js in /Users/josh/repos/generator-node/generators/app/index.js to a dynamic import() which is available in all CommonJS modules.
``` 

...so using the latest `yeoman-generator` dependency is blocked on #298.

---

I can't promise exactly when we'll resolve #265 and unblock this issue, but I'm hoping it'll be Soon ™. In the meantime downgraded `npm install -g yo@4.3.1 generator-generator` does seem to fix this issue. I've hidden other comments in this thread to emphasize that. Cheers! 🎩

**Comment by JoshuaKGoldberg** [comment]
Oh, and this is the stack locally for debugging:

```plaintext
 TypeError: generator.run is not a function
      at runGenerator (/Users/josh/repos/generator-generator/node_modules/generator-node/node_modules/yeoman-generator/lib/index.js:36:15)
      at module.exports.composeWith (/Users/josh/repos/generator-generator/node_modules/generator-node/node_modules/yeoman-generator/lib/index.js:1292:7)
      at module.exports.default (/Users/josh/repos/generator-generator/node_modules/generator-node/generators/app/index.js:332:12)
      at Object.<anonymous> (/Users/josh/repos/generator-generator/node_modules/generator-node/node_modules/yeoman-generator/lib/index.js:991:25)
      at /Users/josh/repos/generator-generator/node_modules/run-async/index.js:49:25
      at new Promise (<anonymous>)
      at /Users/josh/repos/generator-generator/node_modules/run-async/index.js:26:19
      at runLoop.add.once.once (/Users/josh/repos/generator-generator/node_modules/generator-node/node_modules/yeoman-generator/lib/index.js:992:11)
      at Immediate.<anonymous> (/Users/josh/repos/yo/node_modules/grouped-queue/lib/subqueue.js:48:34)
      at process.processImmediate (node:internal/timers:483:21)
```

Captured in `yo`'s `const onError`.
